### PR TITLE
chore: modern publishing

### PR DESCRIPTION
**Pull request by gregberge**

### CODE REVIEW

**Comment by gregberge** [comment]
@JakobJingleheimer I think it is better to provide the two formats. This is the way I build all my library, do you see any problem?

**Comment by JakobJingleheimer** [comment]
It is not better—it's much worse for several reasons. I actually just wrote an article on this very topic 🙂

https://dev.to/jakobjingleheimer/configuring-commonjs-es-modules-for-nodejs-12ed#esm-source-and-both-cjs-amp-esm-distribution

**Comment by gregberge** [comment]
> @JakobJingleheimer I think it is better to provide the two formats. This is the way I build all my library, do you see any problem?

Also it is an intermediary step before publishing only ESM in next major, I am waiting ~ mid 2022 to do it.

**Comment by JakobJingleheimer** [comment]
In the case for this repo at least, distributing both CJS & ESM vs only ESM-compatible CJS, it makes no difference in terms of a path to ESM-only distribution in future.

But the TLDR for distributing both is "don't". There are no benefits and only problems, some of which are small and guaranteed, others are uncommon but potentially very bad and utterly baffling.

**Comment by gregberge** [comment]
I understand @JakobJingleheimer, but for me CJS is the past. I would rather prefer only distributing ESM than distributing only CJS (even if it is compatible).

**Comment by JakobJingleheimer** [comment]
Oh sure. I'm not saying choose CJS over ESM forever; just for however long you want to support both, distribute only CJS (with properly named exports).

PS I'm an implementer on the ESM / Loaders team 😉

**Comment by gregberge** [comment]
The the only problem distributing both is duplicated code if user has a bad builder setup isn't it?

I honestly don't know if as of today I can drop support for CJS? What do you think?

**Comment by gregberge** [comment]
This package will now be ESM only, see #22

**Pull request closed without merging**
